# -*- coding: utf-8 -*-
"""ICU

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/10iSubEf4_4Qppf2CkJ6eUCbvUlp8tsoX

PROCESO DE ICU
"""

#Importar librerias
import pandas as pd
import numpy as np
import matplotlib.pyplot as plt
import seaborn as sns
from sklearn.metrics import r2_score, mean_squared_error

# Cargar el archivo archivo de excel
df = pd.read_excel('Datos ICU.xlsx')
df.head()

# @title
# Renombrar columnas X1 [1/T]; Y1 [Ln(K)]; X2 [1/T]2	Y2 [Ln(K)]2

Datos = df.rename(columns={
    'X1 [1/T]':        'X1',
    'Y1 [Ln(K)]1':     'Y1',
    'X2 [1/T]2':       'X2',
    'Y2 [Ln(K)]2':     'Y2',
})

# Verifica que quedaron bien
print(Datos.columns.tolist())

# Verificamos el cambio de nombres de las columanas
Datos.head()

# @title
plt.figure(figsize=(7,5))
plt.scatter(Datos['X1'], Datos['Y1'], color='blue')
plt.xlabel('X1')
plt.ylabel('Y1')
plt.title('X1 vs Y1')
plt.grid(True)
plt.show()

# @title
plt.figure(figsize=(7,5))
plt.scatter(Datos['X2'], Datos['Y2'], color='red')
plt.xlabel('X2')
plt.ylabel('Y2')
plt.title('X2 vs Y2')
plt.grid(True)
plt.show()

# @title
# Filtramos filas válidas por si hay nulos
mask_1 = Datos[['X1','Y1']].dropna()
x1, y1 = mask_1['X1'].values, mask_1['Y1'].values

# Ajuste lineal: y = m*x + b
m1, b1 = np.polyfit(x1, y1, 1)

# Puntos para la recta
x1_line = np.linspace(x1.min(), x1.max(), 100)
y1_line = m1 * x1_line + b1

plt.figure(figsize=(7,5))
plt.scatter(x1, y1, color='blue', label='Datos')
plt.plot(x1_line, y1_line, color='black', linewidth=2, label=f'y = {m1:.4f}x + {b1:.4f}')
plt.xlabel('X1')
plt.ylabel('Y1')
plt.title('X1 vs Y1 (con línea de tendencia)')
plt.grid(True)
plt.legend()
plt.show()

# @title
# Filtramos filas válidas por si hay nulos
mask_2 = Datos[['X2','Y2']].dropna()
x2, y2 = mask_2['X2'].values, mask_2['Y2'].values

# Ajuste lineal: y = m*x + b
m2, b2 = np.polyfit(x2, y2, 1)

# Puntos para la recta
x2_line = np.linspace(x2.min(), x2.max(), 100)
y2_line = m2 * x2_line + b2

plt.figure(figsize=(7,5))
plt.scatter(x2, y2, color='red', label='Datos')
plt.plot(x2_line, y2_line, color='black', linewidth=2, label=f'y = {m2:.4f}x + {b2:.4f}')
plt.xlabel('X2')
plt.ylabel('Y2')
plt.title('X2 vs Y2 (con línea de tendencia)')
plt.grid(True)
plt.legend()
plt.show()

# @title
def metrics_lineal(df, xcol, ycol, nombre):
    # Filtrar válidos
    d = df[[xcol, ycol]].dropna()
    x = d[xcol].values
    y = d[ycol].values

    # Ajuste lineal y = m*x + b
    m, b = np.polyfit(x, y, 1)
    y_hat = m * x + b

    # Métricas
    r2 = r2_score(y, y_hat)
    rmse = np.sqrt(mean_squared_error(y, y_hat))

    print(f"[{nombre}] y = {m:.6f} x + {b:.6f} | R² = {r2:.5f} | RMSE = {rmse:.5f}")

# Ejecutar para ambas parejas
metrics_lineal(Datos, "X1", "Y1", "X1 vs Y1")
metrics_lineal(Datos, "X2", "Y2", "X2 vs Y2")

# @title
# Datos válidos
d1 = Datos[['X1','Y1']].dropna()
x1 = d1['X1'].values
y1 = d1['Y1'].values

# Ajuste lineal
m1, b1 = np.polyfit(x1, y1, 1)
y1_hat = m1 * x1 + b1

# Métricas
r2_1 = r2_score(y1, y1_hat)
rmse_1 = np.sqrt(mean_squared_error(y1, y1_hat))

# Línea para graficar
x1_line = np.linspace(x1.min(), x1.max(), 100)
y1_line = m1 * x1_line + b1

plt.figure(figsize=(7,5))
plt.scatter(x1, y1, color='blue', label='Datos')
plt.plot(x1_line, y1_line, color='black', linewidth=2, label=f"y = {m1:.4f}x + {b1:.4f}")

plt.xlabel('X1')
plt.ylabel('Y1')
plt.title('X1 vs Y1 (con línea de tendencia)')
plt.grid(True)
plt.legend()

# Texto con métricas dentro del gráfico (caja)
texto = f"R² = {r2_1:.4f}\nRMSE = {rmse_1:.4f}"
plt.gca().text(
    0.02, 0.98, texto,
    transform=plt.gca().transAxes,
    verticalalignment='top',
    bbox=dict(boxstyle='round', facecolor='white', alpha=0.8)
)

plt.show()

# @title
# Datos válidos
d2 = Datos[['X2','Y2']].dropna()
x2 = d2['X2'].values
y2 = d2['Y2'].values

# Ajuste lineal
m2, b2 = np.polyfit(x2, y2, 1)
y2_hat = m2 * x2 + b2

# Métricas
r2_2 = r2_score(y2, y2_hat)
rmse_2 = np.sqrt(mean_squared_error(y2, y2_hat))

# Línea para graficar
x2_line = np.linspace(x2.min(), x2.max(), 100)
y2_line = m2 * x2_line + b2

plt.figure(figsize=(7,5))
plt.scatter(x2, y2, color='red', label='Datos')
plt.plot(x2_line, y2_line, color='black', linewidth=2, label=f"y = {m2:.4f}x + {b2:.4f}")

plt.xlabel('X2')
plt.ylabel('Y2')
plt.title('X2 vs Y2 (con línea de tendencia)')
plt.grid(True)
plt.legend()

# Texto con métricas dentro del gráfico (caja)
texto = f"R² = {r2_2:.4f}\nRMSE = {rmse_2:.4f}"
plt.gca().text(
    0.02, 0.98, texto,
    transform=plt.gca().transAxes,
    verticalalignment='top',
    bbox=dict(boxstyle='round', facecolor='white', alpha=0.8)
)

plt.show()

# @title
import numpy as np
from sklearn.metrics import r2_score

# --- Calcular m, b, R2 para X1-Y1 ---
d1 = Datos[['X1','Y1']].dropna()
x1 = d1['X1'].values
y1 = d1['Y1'].values

m1, b1 = np.polyfit(x1, y1, 1)
y1_pred = m1 * x1 + b1
r2_1 = r2_score(y1, y1_pred)

# --- Calcular m, b, R2 para X2-Y2 ---
d2 = Datos[['X2','Y2']].dropna()
x2 = d2['X2'].values
y2 = d2['Y2'].values

m2, b2 = np.polyfit(x2, y2, 1)
y2_pred = m2 * x2 + b2
r2_2 = r2_score(y2, y2_pred)

# --- Imprimir resultados ---
print(f"Recta 1 (X1-Y1):   m={m1:.4f}, b={b1:.4f}, R²={r2_1:.5f}")
print(f"Recta 2 (X2-Y2):   m={m2:.4f}, b={b2:.4f}, R²={r2_2:.5f}")

# --- Detectar cuál es mejor ---
if r2_1 > r2_2:
    mejor = "Datos 1"
    peor  = "Datos 2"
else:
    mejor = "Datos 2"
    peor  = "Datos 1"

print(f"\nLa mejor tendencia lineal es: {mejor}")
print(f"La tendencia que se va a reajustar es: {peor}")

# @title
# --- 1) Recalcular (por seguridad) m, b, R² de ambas rectas ---
d1 = Datos[['X1','Y1']].dropna()
x1, y1 = d1['X1'].values, d1['Y1'].values
m1, b1 = np.polyfit(x1, y1, 1)
y1_hat = m1 * x1 + b1
r2_1 = r2_score(y1, y1_hat)
rmse_1 = np.sqrt(mean_squared_error(y1, y1_hat))

d2 = Datos[['X2','Y2']].dropna()
x2, y2 = d2['X2'].values, d2['Y2'].values
m2, b2 = np.polyfit(x2, y2, 1)
y2_hat = m2 * x2 + b2
r2_2 = r2_score(y2, y2_hat)
rmse_2 = np.sqrt(mean_squared_error(y2, y2_hat))

print(f"[X1–Y1] m={m1:.6f}, b={b1:.6f}, R²={r2_1:.5f}, RMSE={rmse_1:.5f}")
print(f"[X2–Y2] m={m2:.6f}, b={b2:.6f}, R²={r2_2:.5f}, RMSE={rmse_2:.5f}")

# --- 2) Identificar la mejor (mayor R²) y la "peor" a reajustar ---
if r2_1 >= r2_2:
    nombre_mejor = "X1–Y1"
    m_best, b_best = m1, b1
    # peor = X2–Y2
    xw, yw = x2, y2
    mw_orig, bw_orig = m2, b2
    r2_w_orig, rmse_w_orig = r2_2, rmse_2
    etiqueta_x, etiqueta_y = "X2", "Y2"
else:
    nombre_mejor = "X2–Y2"
    m_best, b_best = m2, b2
    # peor = X1–Y1
    xw, yw = x1, y1
    mw_orig, bw_orig = m1, b1
    r2_w_orig, rmse_w_orig = r2_1, rmse_1
    etiqueta_x, etiqueta_y = "X1", "Y1"

print(f"\nMejor tendencia (por R²): {nombre_mejor}")
print("La otra será reajustada para ser paralela a la mejor.")

# --- 3) Reajuste paralelo en la "peor": misma pendiente m_best, intercepto óptimo ---
b_parallel = yw.mean() - m_best * xw.mean()       # b* = ȳ - m_best * x̄
y_parallel = m_best * xw + b_parallel

# Métricas del reajuste paralelo (sobre la serie 'peor')
r2_parallel = r2_score(yw, y_parallel)
rmse_parallel = np.sqrt(mean_squared_error(yw, y_parallel))

print(f"\n[Reajuste paralelo sobre {etiqueta_x}–{etiqueta_y}]")
print(f"Pendiente fijada (m_best) = {m_best:.6f}")
print(f"Nuevo intercepto (b_parallel) = {b_parallel:.6f}")
print(f"R² paralelo = {r2_parallel:.5f} | RMSE paralelo = {rmse_parallel:.5f}")

# --- 4) Gráfico: datos 'peor' con su recta original y la paralela reajustada ---
xw_line = np.linspace(xw.min(), xw.max(), 100)
y_line_original = mw_orig * xw_line + bw_orig
y_line_parallel = m_best * xw_line + b_parallel

plt.figure(figsize=(8,5))
plt.scatter(xw, yw, color='#1f77b4', alpha=0.85, label='Datos')
plt.plot(xw_line, y_line_original, '--', color='gray',
         label=f"Original: y={mw_orig:.4f}x+{bw_orig:.4f}\nR²={r2_w_orig:.4f}, RMSE={rmse_w_orig:.4f}")
plt.plot(xw_line, y_line_parallel, color='black', linewidth=2,
         label=f"Paralela (m={m_best:.4f}): y={m_best:.4f}x+{b_parallel:.4f}\nR²={r2_parallel:.4f}, RMSE={rmse_parallel:.4f}")

plt.xlabel(etiqueta_x)
plt.ylabel(etiqueta_y)
plt.title(f"Reajuste paralelo sobre {etiqueta_x}–{etiqueta_y} (pendiente igual a {nombre_mejor})")
plt.grid(True, linestyle='--', alpha=0.4)
plt.legend()
plt.show()

# @title
# 1) Métricas de ambas
d1 = Datos[['X1','Y1']].dropna(); x1, y1 = d1['X1'].values, d1['Y1'].values
m1, b1 = np.polyfit(x1, y1, 1); y1_hat = m1*x1 + b1; r2_1 = r2_score(y1, y1_hat)

d2 = Datos[['X2','Y2']].dropna(); x2, y2 = d2['X2'].values, d2['Y2'].values
m2, b2 = np.polyfit(x2, y2, 1); y2_hat = m2*x2 + b2; r2_2 = r2_score(y2, y2_hat)

# 2) Elegir mejor y peor
if r2_1 >= r2_2:
    # Mejor: X1–Y1; Reajustar: X2–Y2
    m_best = m1
    xw, yw = x2, y2
    nombre_peor = "X2–Y2"
    r2_peor_orig = r2_2
else:
    # Mejor: X2–Y2; Reajustar: X1–Y1
    m_best = m2
    xw, yw = x1, y1
    nombre_peor = "X1–Y1"
    r2_peor_orig = r2_1

# 3) Intercepto óptimo con pendiente fija m_best
b_star = yw.mean() - m_best * xw.mean()

# 4) R² máximo alcanzable con pendiente fija (paralela)
y_parallel = m_best * xw + b_star
r2_parallel = r2_score(yw, y_parallel)

print(f"[{nombre_peor}] R² original = {r2_peor_orig:.5f}  ->  R² paralelo (máximo posible con m fija) = {r2_parallel:.5f}")
print(f"Pendiente fija m_best = {m_best:.6f} | Intercepto óptimo b* = {b_star:.6f}")

# @title
# --- 1) Calcular m, b, R2 originales ---
d1 = Datos[['X1','Y1']].dropna()
x1, y1 = d1['X1'].values, d1['Y1'].values
m1, b1 = np.polyfit(x1, y1, 1)
r2_1 = r2_score(y1, m1*x1 + b1)

d2 = Datos[['X2','Y2']].dropna()
x2, y2 = d2['X2'].values, d2['Y2'].values
m2, b2 = np.polyfit(x2, y2, 1)
r2_2 = r2_score(y2, m2*x2 + b2)

# --- 2) Identificar mejor y peor ---
if r2_1 >= r2_2:
    m_best = m1
    xw, yw = x2, y2            # peor
    nombre = "X2–Y2"
    r2_peor = r2_2
else:
    m_best = m2
    xw, yw = x1, y1            # peor
    nombre = "X1–Y1"
    r2_peor = r2_1

print(f"La serie peor es: {nombre} (R² original = {r2_peor:.5f})")

# --- 3) Calcular intercepto óptimo para pendiente fija ---
b_star = yw.mean() - m_best * xw.mean()
print(f"Intercepto óptimo b* = {b_star:.6f}")

# --- 4) Evaluar si b* es óptimo mediante barrido ---
b_values = np.linspace(b_star - 2, b_star + 2, 200)   # rango alrededor del óptimo
r2_values = []

for b_test in b_values:
    y_pred = m_best * xw + b_test
    r2_values.append(r2_score(yw, y_pred))

# --- 5) Encontrar el mejor R² del barrido ---
idx_best = np.argmax(r2_values)
b_best_scan = b_values[idx_best]
r2_best_scan = r2_values[idx_best]

print(f"Mejor R² encontrado en barrido = {r2_best_scan:.6f} con b = {b_best_scan:.6f}")

# --- 6) Gráfico para visualizar si b* es el óptimo ---
plt.figure(figsize=(8,5))
plt.plot(b_values, r2_values, label='R² vs b (pendiente fija)')
plt.axvline(b_star, color='red', linestyle='--', label=f"b* = {b_star:.6f}")
plt.xlabel("Intercepto b")
plt.ylabel("R²")
plt.title(f"Validación del óptimo para {nombre}")
plt.legend()
plt.grid(True)
plt.show()

# @title
import numpy as np
import matplotlib.pyplot as plt
from sklearn.metrics import r2_score, mean_squared_error

# --- Datos (usa tu DF 'Datos') ---
d1 = Datos[['X1','Y1']].dropna(); x1, y1 = d1['X1'].values, d1['Y1'].values
d2 = Datos[['X2','Y2']].dropna(); x2, y2 = d2['X2'].values, d2['Y2'].values

# --- Ajustes originales ---
m1, b1 = np.polyfit(x1, y1, 1); y1_hat = m1*x1 + b1
r2_1 = r2_score(y1, y1_hat); rmse_1 = np.sqrt(mean_squared_error(y1, y1_hat))

m2, b2 = np.polyfit(x2, y2, 1); y2_hat = m2*x2 + b2
r2_2 = r2_score(y2, y2_hat); rmse_2 = np.sqrt(mean_squared_error(y2, y2_hat))

# --- Elegir mejor y peor ---
if r2_1 >= r2_2:
    # Mejor: X1–Y1 ; Peor: X2–Y2
    m_best, b_best = m1, b1
    xw, yw = x2, y2
    mw_orig, bw_orig = m2, b2
    r2_w_orig, rmse_w_orig = r2_2, rmse_2
    lab_mejor, lab_peor = "X1–Y1", "X2–Y2"
else:
    # Mejor: X2–Y2 ; Peor: X1–Y1
    m_best, b_best = m2, b2
    xw, yw = x1, y1
    mw_orig, bw_orig = m1, b1
    r2_w_orig, rmse_w_orig = r2_1, rmse_1
    lab_mejor, lab_peor = "X2–Y2", "X1–Y1"

# --- Reajuste paralelo sobre la 'peor' (pendiente fija = m_best) ---
b_par = yw.mean() - m_best * xw.mean()
y_par = m_best * xw + b_par
r2_par = r2_score(yw, y_par)
rmse_par = np.sqrt(mean_squared_error(yw, y_par))

# --- Preparar líneas para graficar ---
xline_best = np.linspace(
    (x1.min() if lab_mejor == "X1–Y1" else x2.min()),
    (x1.max() if lab_mejor == "X1–Y1" else x2.max()),
    100
)
yline_best = m_best * xline_best + b_best

xline_peor = np.linspace(xw.min(), xw.max(), 100)
yline_peor_orig = mw_orig * xline_peor + bw_orig
yline_peor_par  = m_best   * xline_peor + b_par

# --- UNA SOLA FIGURA ---
plt.figure(figsize=(10,6))

# Puntos
plt.scatter(x1, y1, color='#1f77b4', alpha=0.85, edgecolor='k', label='Datos X1–Y1')
plt.scatter(x2, y2, color='#d62728', alpha=0.85, edgecolor='k', label='Datos X2–Y2')

# Línea de la mejor (negra)
plt.plot(xline_best, yline_best, color='black', linewidth=2,
         label=f"Mejor {lab_mejor}: y={m_best:.4f}x+{b_best:.4f}")

# Línea original de la 'peor' (gris punteado)
plt.plot(xline_peor, yline_peor_orig, '--', color='gray',
         label=f"Original {lab_peor}: y={mw_orig:.4f}x+{bw_orig:.4f}\nR²={r2_w_orig:.4f} | RMSE={rmse_w_orig:.4f}")

# Línea paralela reajustada de la 'peor' (verde)
plt.plot(xline_peor, yline_peor_par, color='green', linewidth=2,
         label=f"Paralela {lab_peor}: y={m_best:.4f}x+{b_par:.4f}\nR²={r2_par:.4f} | RMSE={rmse_par:.4f}")

plt.title("Comparación en UNA sola gráfica: datos, mejor línea y paralela reajustada")
plt.xlabel("X (X1 y X2)")
plt.ylabel("Y (Y1 y Y2)")
plt.grid(True, linestyle='--', alpha=0.4)
plt.legend(loc='best')
plt.tight_layout()
plt.show()